/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_mesg_2eproto__INCLUDED
#define PROTOBUF_C_mesg_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _Mesg__Online Mesg__Online;
typedef struct _Mesg__Offline Mesg__Offline;
typedef struct _Mesg__OnlineAck Mesg__OnlineAck;


/* --- enums --- */


/* --- messages --- */

struct  _Mesg__Online
{
  ProtobufCMessage base;
  char *cid;
  char *token;
  char *version;
  char *appkey;
};
#define MESG__ONLINE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mesg__online__descriptor) \
    , NULL, NULL, NULL, NULL }


struct  _Mesg__Offline
{
  ProtobufCMessage base;
  protobuf_c_boolean has_code;
  int32_t code;
  char *msg;
  char *appkey;
};
#define MESG__OFFLINE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mesg__offline__descriptor) \
    , 0,0, NULL, NULL }


struct  _Mesg__OnlineAck
{
  ProtobufCMessage base;
  protobuf_c_boolean has_code;
  int32_t code;
  char *msg;
};
#define MESG__ONLINE_ACK__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mesg__online_ack__descriptor) \
    , 0,0, NULL }


/* Mesg__Online methods */
void   mesg__online__init
                     (Mesg__Online         *message);
size_t mesg__online__get_packed_size
                     (const Mesg__Online   *message);
size_t mesg__online__pack
                     (const Mesg__Online   *message,
                      uint8_t             *out);
size_t mesg__online__pack_to_buffer
                     (const Mesg__Online   *message,
                      ProtobufCBuffer     *buffer);
Mesg__Online *
       mesg__online__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mesg__online__free_unpacked
                     (Mesg__Online *message,
                      ProtobufCAllocator *allocator);
/* Mesg__Offline methods */
void   mesg__offline__init
                     (Mesg__Offline         *message);
size_t mesg__offline__get_packed_size
                     (const Mesg__Offline   *message);
size_t mesg__offline__pack
                     (const Mesg__Offline   *message,
                      uint8_t             *out);
size_t mesg__offline__pack_to_buffer
                     (const Mesg__Offline   *message,
                      ProtobufCBuffer     *buffer);
Mesg__Offline *
       mesg__offline__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mesg__offline__free_unpacked
                     (Mesg__Offline *message,
                      ProtobufCAllocator *allocator);
/* Mesg__OnlineAck methods */
void   mesg__online_ack__init
                     (Mesg__OnlineAck         *message);
size_t mesg__online_ack__get_packed_size
                     (const Mesg__OnlineAck   *message);
size_t mesg__online_ack__pack
                     (const Mesg__OnlineAck   *message,
                      uint8_t             *out);
size_t mesg__online_ack__pack_to_buffer
                     (const Mesg__OnlineAck   *message,
                      ProtobufCBuffer     *buffer);
Mesg__OnlineAck *
       mesg__online_ack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mesg__online_ack__free_unpacked
                     (Mesg__OnlineAck *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Mesg__Online_Closure)
                 (const Mesg__Online *message,
                  void *closure_data);
typedef void (*Mesg__Offline_Closure)
                 (const Mesg__Offline *message,
                  void *closure_data);
typedef void (*Mesg__OnlineAck_Closure)
                 (const Mesg__OnlineAck *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor mesg__online__descriptor;
extern const ProtobufCMessageDescriptor mesg__offline__descriptor;
extern const ProtobufCMessageDescriptor mesg__online_ack__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_mesg_2eproto__INCLUDED */
